#!/bin/bash

##setup mpi environment
##none, source /usr/usc/openmpi/1.8.8/setup.sh

source setup/setup_UCVMC.sh

mkdir -p $UCVM_INSTALL_PATH

mkdir  $TOP_UCVM_DIR/model
cd $TOP_UCVM_DIR/model
git clone https://github.com/SCECcode/UCVMC.git -b forGFM

# 6th is cvmsi,
# 8th is cvmh
cd $UCVM_SRC_PATH/largefiles
./get_large_files.py << EOB 
y
n
n
n
n
y
n
y
EOB

### cd $UCVM_SRC_PATH/largefiles; ./check_largefiles_md5.py
cd $UCVM_SRC_PATH/largefiles; ./stage_large_files.py

cd $UCVM_SRC_PATH
./ucvm_setup.py -d -a << EOF &> ucvm_setup_install.log
$UCVM_INSTALL_PATH
EOF

cd $UCVM_SRC_PATH; make check

echo "..EXITING.."
exit
