#!/bin/bash

source setup/setup_UCVM.sh

mkdir -p $UCVM_INSTALL_PATH

mkdir -p $TOP_UCVM_DIR/model
cd $TOP_UCVM_DIR/model

git clone https://github.com/SCECcode/ucvm.git UCVM

cd $UCVM_SRC_PATH/largefiles
if [ "$(uname)" == "Darwin" ]; then
./get_largefiles.py -m cvms,cvms5,cvmsi
else
./get_largefiles.py -m wfcvm,cca,sfcvm,cvms,cvmsi,cvms5,cvmh,ivlsu,cvlsu,albacore,sjfz,cvmhlabn,cvmhsgbn,cvmhvbn,cvmhibbn,cvmhrbn,cvmhsbbn,cvmhsbcbn,cvmhsmbn,cvmhstbn,canvas,uwsfbcvm,uwlinca,cs248
fi


if [ "$(uname)" != "Darwin" ]; then
  cd $UCVM_SRC_PATH/largefiles; ./check_largefiles_md5.py
fi
cd $UCVM_SRC_PATH/largefiles; ./stage_largefiles.py

## because of the new PROJ/ucvm_setup.py
unset PROJ_LIB

### for system that has really old gcc
#This is for linux/moho
if command -v gcc10-gcc &> /dev/null; then
  echo "gcc10-gcc exists" 
  export CC=gcc10-gcc
  export CXX=gcc10-g++
else
  if command -v gcc-10 &> /dev/null; then
    echo "gcc-10 exists" 
    export CC=gcc-10
    export CXX=g++-10
  else
    echo "use default gcc" 
  fi
fi
  
export PYTHONUNBUFFERED=TRUE
cd $UCVM_SRC_PATH
./ucvm_setup.py -a -d -p $UCVM_INSTALL_PATH >& ucvm_setup_install.log 

if [ "$(uname)" == "Darwin" ]; then
## proj4 can not handle this
  unset PROJ_LIB
fi

cd $UCVM_SRC_PATH; make runcheck

## make sure everything in installed model is globally readable
chmod -R +r $UCVM_INSTALL_PATH/model

## only if it is on my local mac
if [ "$(uname)" == "Darwin" ]; then
    source conf/ucvm_env.sh
## anaconda2 needs this but breaks proj4
##??    export PROJ_LIB=/Users/mei/anaconda2/share/proj
##
    conda install -y numpy matplotlib basemap basemap-data-hires
    cd $UCVM_INSTALL_PATH
    git clone https://github.com/SCECcode/ucvm_plotting.git
    cd ucvm_plotting
    ./unpack-dist
fi

echo "..EXITING.."
exit
